#!/bin/bash

cmd=$1
arg=""

while shift; do
    arg="$arg $1"
done

if [ ! -f "instlog" ]; then
#    echo "instlog file doesn't exist. makeing the file..."
    touch "instlog"
    echo "#!/bin/bash" >> instlog
fi

sudo $cmd install$arg && echo "sudo $cmd install$arg" >> instlog
