#!/bin/bash

cmd=$1
arg=""
logfile="/var/log/inst.log"

shift
arg="$@"

if [ ! -f "$logfile" ]; then
    sudo touch "$logfile"
    echo "#!/bin/bash" | sudo tee -a "$logfile"
fi

if sudo "$cmd" install $arg; then
    echo "sudo $cmd install $arg" | sudo tee -a "$logfile"
fi
